services:
  # The MongoDB Database Service
  mongo:
    image: mongo:4.4
    container_name: mongodb_scheduler
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  # The Discord Bot Service
  bot:
    build: .
    container_name: discord_scheduler_bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./attachments:/app/attachments

volumes:
  mongo-data: